name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: AarushCh

          # Core
          base: header, activity, community, repositories

          # Commits & activity
          commits_authoring: true

          # Languages
          plugin_languages: true
          plugin_languages_details: bytes-size, percentage

          # Achievements
          plugin_achievements: true
          plugin_achievements_threshold: C

          # Not using external plugins
          plugin_streak: false
          plugin_isocalendar: false

          config_timezone: Asia/Kolkata