name: generate metrics

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: AarushCh
          template: classic
          base: header, activity, community
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_streak: yes
          plugin_activity: yes
          config_timezone: Asia/Kolkata
          filename: metrics.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output-metrics
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}